// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXrGskv9mPRNNI4-DWU73iO1LkGjPyspU',
    appId: '1:937488511257:web:3264a097e36d2aeafb9588',
    messagingSenderId: '937488511257',
    projectId: 'techwiz-pawfect-care',
    authDomain: 'techwiz-pawfect-care.firebaseapp.com',
    storageBucket: 'techwiz-pawfect-care.firebasestorage.app',
    measurementId: 'G-1QL9JYB4N1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzfVPh5RftNzoOg_rOkdze_eSU9gAUE8c',
    appId: '1:937488511257:android:491e09387d350818fb9588',
    messagingSenderId: '937488511257',
    projectId: 'techwiz-pawfect-care',
    storageBucket: 'techwiz-pawfect-care.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGQ4l05ppmUgOZv-bRDqWlzvSVSIxU1Us',
    appId: '1:937488511257:ios:8ceb1890cdbdd855fb9588',
    messagingSenderId: '937488511257',
    projectId: 'techwiz-pawfect-care',
    storageBucket: 'techwiz-pawfect-care.firebasestorage.app',
    androidClientId: '937488511257-3l8iqdod46h5veiahe5nqt7t7gf2paog.apps.googleusercontent.com',
    iosClientId: '937488511257-h1ddfk5e9c1qcqnufced2ts9dh5v6ndj.apps.googleusercontent.com',
    iosBundleId: 'com.example.pawfectCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGQ4l05ppmUgOZv-bRDqWlzvSVSIxU1Us',
    appId: '1:937488511257:ios:8ceb1890cdbdd855fb9588',
    messagingSenderId: '937488511257',
    projectId: 'techwiz-pawfect-care',
    storageBucket: 'techwiz-pawfect-care.firebasestorage.app',
    androidClientId: '937488511257-3l8iqdod46h5veiahe5nqt7t7gf2paog.apps.googleusercontent.com',
    iosClientId: '937488511257-h1ddfk5e9c1qcqnufced2ts9dh5v6ndj.apps.googleusercontent.com',
    iosBundleId: 'com.example.pawfectCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXrGskv9mPRNNI4-DWU73iO1LkGjPyspU',
    appId: '1:937488511257:web:e9fae2e3232749fbfb9588',
    messagingSenderId: '937488511257',
    projectId: 'techwiz-pawfect-care',
    authDomain: 'techwiz-pawfect-care.firebaseapp.com',
    storageBucket: 'techwiz-pawfect-care.firebasestorage.app',
    measurementId: 'G-1HR108RVW2',
  );
}
